CREATE TABLE meta_info_seo
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    meta_title  VARCHAR(255),
    name_link   VARCHAR(255),
    description VARCHAR(255),
    image_id    UUID,
    CONSTRAINT pk_meta_info_seo PRIMARY KEY (id)
);

ALTER TABLE meta_info_seo
    ADD CONSTRAINT FK_META_INFO_SEO_ON_IMAGE FOREIGN KEY (image_id) REFERENCES images (id);