services:
  server:
    image: dukeofjava/imalchemy_server:0.1
    container_name: server
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=imalchemy
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=secret
      - FILE_UPLOAD_LOCATION=/app/uploads
    volumes:
      - ./src/main/resources/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: db
    restart: on-failure
    environment:
      - POSTGRES_DB=imalchemy
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
