server:
  port: 9090

spring:
  application:
    name: PixelFreebies-Service

  config:
    import: application-dev.yml,application-dev.yml,application-test.yml

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  threads:
    virtual:
      enabled: true

base:
  url: /api/v1

cors:
  origin:
    url:
      permitted: ${CORS_ORIGIN_URL:http://localhost:3000} # comma-separated
