--- ###Profile
spring:
  config:
    activate:
      on-profile: dev

--- ###Datasource
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:pixelfreebies_service}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:qaz@123QAZ}

  # hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${SPRING_PROPERTIES_HIBERNATE_SHOW_SQL:false}
        format_sql: ${SPRING_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
    hibernate:
      ddl-auto: validate

  # flyway
  flyway:
    baseline-on-migrate: true
    enabled: true

--- ###File
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    location: ${FILE_UPLOAD_LOCATION:C:\Users\Al-Khalsi\Desktop\WebSite\pixelfreebies-client\public\img}
ftp:
  host: 2193182589.cloudydl.com
  username: pz20122
  password: xzAJ8nrN

--- #Swagger
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method
#    tagsSorter: alpha
#    disable-swagger-default-url: true

--- ###Custom Variables
token:
  jwt:
    expires_in: 1440 # 60min * 24hours = 1440min
