server:
  port: 9090

spring:
  application:
    name: PixelFreebies-Service

  config:
    import: application-prod.yml,application-dev.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

base:
  url: /api/v1

cors:
  origin:
    url:
      permitted: ${CORS_ORIGIN_URL:localhost:3000}
