--- ###Profile
spring:
  config:
    activate:
      on-profile: dev

--- ###Datasource
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:pixelfreebies_service}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:qaz@123QAZ}

  # hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${SPRING_PROPERTIES_HIBERNATE_SHOW_SQL:false}
        format_sql: ${SPRING_PROPERTIES_HIBERNATE_FORMAT_SQL:false}
    hibernate:
      ddl-auto: validate

  # flyway
  flyway:
    baseline-on-migrate: true
    enabled: true

--- ###File
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    location: ${FILE_UPLOAD_LOCATION:C:\Users\Al-Khalsi\Desktop\WebSite\pixelfreebies-client\public\img}
#    location: ${FILE_UPLOAD_LOCATION:/home/simi/uploads}

s3:
  bucket: c567062
  endpointUrl: ${S3_ENDPOINT_URL:dummy}
  accessKey: ${S3_ACCESS_KEY:dummy}
  secretKey: ${S3_SECRET_KEY:dummy}

--- ###Email
spring:
  mail:
    username: ${SMTP_USERNAME:pixelfreebies@gmail.com}
    password: ${SMTP_PASSWORD}
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  service:
    provider: google

--- ###Custom Variables
token:
  jwt:
    expires_in: 1440 # Token expiration time in minutes (1440 minutes = 24 hours)
