server:
  port: 8080

spring:
  application:
    name: PNG-Downloading-Platform

  config:
    import: application-prod.yml,application-dev.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

base:
  url: /api/v1
