server:
  port: 8080

spring:
  application:
    name: PNG-Downloading-Platform

  config:
    import: application-prod.yml,application-dev.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{dd-MMM-yyyy HH:mm:ss.SSS}) %blue(%-5level) %red([ %thread ]) %yellow(%logger{ 15 }) - %msg%n}}

base:
  url: /api/v1
