--- ###Profile
spring:
  config:
    activate:
      on-profile: prod

--- ###Datasource
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # hibernate
  jpa:
    hibernate:
      ddl-auto: validate

  # flyway
  flyway:
    baseline-on-migrate: true
    enabled: true

--- ###File
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    location: ${FILE_UPLOAD_LOCATION:/app/uploads}

--- ###Custom Variables
token:
  jwt:
    expires_in: 20
