--- ###Profile
spring:
  config:
    activate:
      on-profile: dev

--- ###Datasource
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:imalchemy}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:qaz@123QAZ}

  # hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  # flyway
  flyway:
    baseline-on-migrate: true
    enabled: true

--- ###File
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    location: "src/main/resources/uploads"

--- #Swagger
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operationsSorter: method
#    tagsSorter: alpha
#    disable-swagger-default-url: true

--- ###Custom Variables
token:
  jwt:
    expires_in: 60
