CREATE TABLE category
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    name          VARCHAR(255),
    description   VARCHAR(255),
    slug          VARCHAR(255),
    icon_url      VARCHAR(255),
    is_active     BOOLEAN                                 NOT NULL,
    display_order INTEGER                                 NOT NULL,
    total_files   INTEGER                                 NOT NULL,
    level         INTEGER                                 NOT NULL,
    is_parent     BOOLEAN DEFAULT TRUE                    NOT NULL,
    parent_id     BIGINT,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE file_colors
(
    file_id         UUID NOT NULL,
    dominant_colors VARCHAR(255)
);

CREATE TABLE files_categories
(
    category_id BIGINT NOT NULL,
    file_id     UUID   NOT NULL,
    CONSTRAINT pk_files_categories PRIMARY KEY (category_id, file_id)
);

ALTER TABLE file
    ADD keywords VARCHAR(255);

ALTER TABLE file
    ADD last_downloaded_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE file
    ADD view_count BIGINT;

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_PARENT FOREIGN KEY (parent_id) REFERENCES category (id);

ALTER TABLE files_categories
    ADD CONSTRAINT fk_filcat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE files_categories
    ADD CONSTRAINT fk_filcat_on_file FOREIGN KEY (file_id) REFERENCES file (id);

ALTER TABLE file_colors
    ADD CONSTRAINT fk_file_colors_on_file FOREIGN KEY (file_id) REFERENCES file (id);

ALTER TABLE file
    ALTER COLUMN average_rating TYPE DECIMAL USING (average_rating::DECIMAL);

ALTER TABLE file
    ALTER COLUMN download_count SET NOT NULL;

ALTER TABLE file
    ALTER COLUMN height SET NOT NULL;

ALTER TABLE file
    ALTER COLUMN is_active SET NOT NULL;

ALTER TABLE file
    ALTER COLUMN width SET NOT NULL;