ALTER TABLE category
DROP
CONSTRAINT fk_category_on_parent;

ALTER TABLE images_categories
DROP
CONSTRAINT fk_imacat_on_category;

ALTER TABLE images_categories
DROP
CONSTRAINT fk_imacat_on_image;

CREATE TABLE image_categories
(
    category_id BIGINT NOT NULL,
    image_id    UUID   NOT NULL,
    CONSTRAINT pk_image_categories PRIMARY KEY (category_id, image_id)
);

CREATE TABLE image_subcategories
(
    image_id       UUID   NOT NULL,
    subcategory_id BIGINT NOT NULL,
    CONSTRAINT pk_image_subcategories PRIMARY KEY (image_id, subcategory_id)
);

CREATE TABLE sub_categories
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    description        VARCHAR(255),
    slug               VARCHAR(255),
    icon_url           VARCHAR(255),
    is_active          BOOLEAN                                 NOT NULL,
    display_order      INTEGER                                 NOT NULL,
    total_files        INTEGER                                 NOT NULL,
    level              INTEGER                                 NOT NULL,
    is_parent          BOOLEAN                                 NOT NULL,
    parent_category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_sub_categories PRIMARY KEY (id)
);

ALTER TABLE sub_categories
    ADD CONSTRAINT FK_SUB_CATEGORIES_ON_PARENT_CATEGORY FOREIGN KEY (parent_category_id) REFERENCES category (id);

ALTER TABLE image_categories
    ADD CONSTRAINT fk_imacat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE image_categories
    ADD CONSTRAINT fk_imacat_on_image FOREIGN KEY (image_id) REFERENCES images (id);

ALTER TABLE image_subcategories
    ADD CONSTRAINT fk_imasub_on_image FOREIGN KEY (image_id) REFERENCES images (id);

ALTER TABLE image_subcategories
    ADD CONSTRAINT fk_imasub_on_sub_category FOREIGN KEY (subcategory_id) REFERENCES sub_categories (id);

DROP TABLE images_categories CASCADE;

ALTER TABLE category
DROP
COLUMN parent_id;