### upload
// @no-log
< {%
    request.variables.set("auth_token", request.variables.get("auth_token"));
%}
POST http://localhost:8080/api/v1/file/upload
Authorization: {{auth_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="imalchemy.png"
Content-Type: image/png

< ../documentation/imalchemy.png
--WebAppBoundary--
