### create user
// @no-log
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "username": "someone",
  "email": "someone",
  "password": "someone"
}

### user by email
// @no-log
GET http://localhost:8080/api/v1/user/someone