name: Build and Push Backend Docker Image

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dukeofjava/pixelfreebies-service

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: backend/.m2
          key: "${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build Docker Image with Jib
      - name: Build Backend Docker Image
        working-directory: backend
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [ "${{ github.ref_name }}" == "main" ]; then
            TAG="${IMAGE_NAME}:${VERSION}"
          else
            HASH=$(echo "${{ github.sha }}" | head -c 7)
            TAG="${IMAGE_NAME}:${VERSION}-dev-${HASH}"
          fi
          echo "Building Docker image: $TAG"
          mvn compile jib:dockerBuild -Dimage=$TAG

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker Image to Registry
      - name: Push Backend Docker Image
        working-directory: backend
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [ "${{ github.ref_name }}" == "main" ]; then
            TAG="${IMAGE_NAME}:${VERSION}"
          else
            HASH=$(echo "${{ github.sha }}" | head -c 7)
            TAG="${IMAGE_NAME}:${VERSION}-dev-${HASH}"
          fi
          echo "Pushing Docker image: $TAG"
          docker push $TAG
