#name: Cleanup Docker Images
#
#on:
#  schedule:
#    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
#  workflow_dispatch:  # Allow manual triggers
#
#jobs:
#  cleanup:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Cleanup old images
#        run: |
#          # Keep only the 5 most recent SHA-tagged images per branch
#          for branch in $(docker image ls ${{ env.IMAGE_NAME }} --format "{{.Tag}}" | grep -o '^[^-]*' | sort -u); do
#            images=$(docker image ls ${{ env.IMAGE_NAME }} --format "{{.Tag}}" | grep "^$branch-" | sort -r | tail -n +6)
#            for tag in $images; do
#              docker image rm ${{ env.IMAGE_NAME }}:$tag
#            done
#          done