name: Build and Push SpringBoot Docker Image

on:
  pull_request:      # Trigger a workflow when a pull request is made
    types: [closed]  # Trigger only when pull requests are closed i.e., merged to main
    branches:
      - main
#  push:              # Trigger a workflow when a commit or push has made on main branch
#    branches:
#      - main
  workflow_dispatch: # Allow triggering a workflow manually in github

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dukeofjava/pixelfreebies-service

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: backend/pixelfreebies-service/.m2
          key: "${{ runner.os }}-maven-${{ hashFiles('backend/pixelfreebies-service/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build Docker Image with Jib
      - name: Build Backend Docker Image
        working-directory: backend/pixelfreebies-service
        env:
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          DATABASE_USERNAME: test_user
          DATABASE_PASSWORD: test_password
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          TAG="${IMAGE_NAME}:${VERSION}"
          echo "Building Docker image: $TAG"
          mvn compile jib:dockerBuild -Dimage=$TAG

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker Image to Registry
      - name: Push Backend Docker Image
        working-directory: backend/pixelfreebies-service
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          TAG="${IMAGE_NAME}:${VERSION}"
          echo "Pushing Docker image with version tag: $TAG"
          docker push $TAG
          LATEST_TAG="${IMAGE_NAME}:latest"
          echo "Pushing Docker image with latest tag: $LATEST_TAG"
          docker tag $TAG $LATEST_TAG
          docker push $LATEST_TAG